// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZSJNAN2bSX3CLHmni1J_XXD972N5sTfY',
    appId: '1:724076943880:web:ea4a3b3dcecf5c63ab0fbd',
    messagingSenderId: '724076943880',
    projectId: 'pro-task-manager-93403',
    authDomain: 'pro-task-manager-93403.firebaseapp.com',
    storageBucket: 'pro-task-manager-93403.firebasestorage.app',
    measurementId: 'G-LFL9106LPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoIgPTO2Vyetph3auc6xxZiG3mFXxuO_k',
    appId: '1:724076943880:android:263245305d617fd1ab0fbd',
    messagingSenderId: '724076943880',
    projectId: 'pro-task-manager-93403',
    storageBucket: 'pro-task-manager-93403.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQqsPKMNo-3CP8rUp4zbYSDB9BvTYCJrs',
    appId: '1:724076943880:ios:2a0658ba06c43eacab0fbd',
    messagingSenderId: '724076943880',
    projectId: 'pro-task-manager-93403',
    storageBucket: 'pro-task-manager-93403.firebasestorage.app',
    iosBundleId: 'com.example.noticeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQqsPKMNo-3CP8rUp4zbYSDB9BvTYCJrs',
    appId: '1:724076943880:ios:2a0658ba06c43eacab0fbd',
    messagingSenderId: '724076943880',
    projectId: 'pro-task-manager-93403',
    storageBucket: 'pro-task-manager-93403.firebasestorage.app',
    iosBundleId: 'com.example.noticeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZSJNAN2bSX3CLHmni1J_XXD972N5sTfY',
    appId: '1:724076943880:web:303fee9393d73bb3ab0fbd',
    messagingSenderId: '724076943880',
    projectId: 'pro-task-manager-93403',
    authDomain: 'pro-task-manager-93403.firebaseapp.com',
    storageBucket: 'pro-task-manager-93403.firebasestorage.app',
    measurementId: 'G-DY8S1N3196',
  );
}
